Rearrange rtSetup for ICC and RTC, add cpuset services

diff --git a/rtSetup/ICC/icc_cpuset b/rtSetup/ICC/icc_cpuset
--- a/rtSetup/ICC/icc_cpuset
+++ b/rtSetup/ICC/icc_cpuset
@@ -47,7 +47,9 @@
 #    29           1            13          61            1            13 
 #    30           1            14          61            1            14 
 #    31           1            15          63            1            15     
-            
+
+set -euo pipefail
+
 # we will use processors 0-7 and 32-39 as the hyperthread system cpus,
 # so we disable processors 40-63. This leaves us 8-31 as single thread processors.
 
@@ -58,8 +60,10 @@ do
 done
 
 #Create and mount the root cpuset
-mkdir -p /dev/cpuset
-mount -t cpuset cpuset /dev/cpuset
+if ! mount | grep -q cpuset; then
+   mkdir -p /dev/cpuset
+   mount -t cpuset cpuset /dev/cpuset
+fi
 cd /dev/cpuset
 
 #############################
@@ -72,9 +76,12 @@ mkdir -p /dev/cpuset/system
 
 # Now move all current tasks to system cpuset
 # Note that this moves pid=1 (init) so all new process created should live here.
-# we suppress the errors from echo b/c they are for dead pids still in tasks
+# We use || true to ignore failures, which are caused by stale PIDs
+# or attempting to move unmovable kernel threads.
 #
-while read i; do /bin/echo -n $i; done < tasks > system/tasks 2> /dev/null
+while read i; do
+   /bin/echo -n $i 2>/dev/null || true
+done < tasks > system/tasks
 
 #A guess at how to setup load balancing 
 echo 0 > cpuset.sched_load_balance
@@ -232,3 +239,5 @@ mkdir -p /dev/cpuset/spare31
 /bin/echo 31 > /dev/cpuset/spare31/cpuset.cpus
 /bin/echo 1 > /dev/cpuset/spare31/cpuset.cpu_exclusive
 /bin/echo 0-1 > /dev/cpuset/spare31/cpuset.mems
+
+echo "cpusets configured successfully"
diff --git a/rtSetup/RTC/rtc_cpuset b/rtSetup/RTC/rtc_cpuset
--- a/rtSetup/RTC/rtc_cpuset
+++ b/rtSetup/RTC/rtc_cpuset
@@ -51,7 +51,9 @@
 #    33           1            25          69            1            25            
 #    34           1            26          70            1            26 
 #    35           1            27          71            1            27 
-            
+
+set -euo pipefail
+
 # we will use processors 0-13 and 36-49 as the hyperthread system cpus (28),
 # so we disable processors 50-71. This leaves us 14-35 (22) as single thread processors.
 
@@ -62,8 +64,10 @@ do
 done
 
 #Create and mount the root cpuset
-mkdir -p /dev/cpuset
-mount -t cpuset cpuset /dev/cpuset
+if ! mount | grep -q cpuset; then
+   mkdir -p /dev/cpuset
+   mount -t cpuset cpuset /dev/cpuset
+fi
 cd /dev/cpuset
 
 #############################
@@ -76,9 +80,12 @@ mkdir -p /dev/cpuset/system
 
 # Now move all current tasks to system cpuset
 # Note that this moves pid=1 (init) so all new process created should live here.
-# we suppress the errors from echo b/c they are for dead pids still in tasks
+# We use || true to ignore failures, which are caused by stale PIDs
+# or attempting to move unmovable kernel threads.
 #
-while read i; do /bin/echo -n $i; done < tasks > system/tasks 2> /dev/null
+while read i; do
+   /bin/echo -n $i 2>/dev/null || true
+done < tasks > system/tasks
 
 #A guess at how to setup load balancing 
 echo 0 > cpuset.sched_load_balance
@@ -216,3 +223,5 @@ mkdir -p /dev/cpuset/tweeterSpeck
 /bin/echo 35 > /dev/cpuset/tweeterSpeck/cpuset.cpus
 /bin/echo 1 > /dev/cpuset/tweeterSpeck/cpuset.cpu_exclusive
 /bin/echo 0-1 > /dev/cpuset/tweeterSpeck/cpuset.mems
+
+echo "cpusets configured successfully"
